LMSRC   = parse.o
LDESBIN = tools.bin

CMYINCUDE  = -I../../../../develop/extra/target/mips-glibc/hardfloat/directfb-1.4.2m/include/directfb/
CMYINCUDE  += -I../include 
a:
	$(CC) -c parse.c $(CMYINCUDE)
	cp *.o ../
